// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Fs.readFileSync("input/Week1/Year2020Day2.sample.txt", "utf8");

var inputList = Belt_Array.keepMap(input.split("\n"), (function (item) {
        var match = item.split(" ");
        if (match.length !== 3) {
          return ;
        }
        var period = match[0];
        var pattern = match[1];
        var password = match[2];
        var match$1 = Belt_Array.map(period.split("-"), Belt_Int.fromString);
        if (match$1.length !== 2) {
          return ;
        }
        var first = match$1[0];
        if (first === undefined) {
          return ;
        }
        var second = match$1[1];
        if (second !== undefined) {
          return [
                  [
                    first,
                    second
                  ],
                  pattern.charAt(0),
                  password
                ];
        }
        
      }));

console.log(inputList);

console.log(Belt_Array.keep(inputList, (function (param) {
            var match = param[0];
            var numberOfChar = param[2].split(param[1]).length - 1 | 0;
            if (match[0] <= numberOfChar) {
              return match[1] >= numberOfChar;
            } else {
              return false;
            }
          })).length);

console.log(Belt_Array.keep(inputList, (function (param) {
            var password = param[2];
            var pattern = param[1];
            var match = param[0];
            var firstMatch = password.charAt(match[0] - 1 | 0) === pattern;
            var secondMatch = password.charAt(match[1] - 1 | 0) === pattern;
            if (firstMatch) {
              if (secondMatch) {
                return false;
              } else {
                return true;
              }
            } else if (secondMatch) {
              return true;
            } else {
              return false;
            }
          })).length);

exports.input = input;
exports.inputList = inputList;
/* input Not a pure module */
