// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

var input = Fs.readFileSync("input/Week1/Year2020Day6.sample.txt", "utf8");

var inputList = Belt_Array.map(Belt_Array.map(Belt_Array.map(input.split("\n\n"), (function (group) {
                return group.split("\n");
              })), (function (group) {
            return Belt_Array.map(group, (function (answers) {
                          return answers.split("");
                        }));
          })), Belt_Array.concatMany);

console.log(Belt_Array.reduce(Belt_Array.map(inputList, (function (group) {
                return Belt_SetString.toArray(Belt_SetString.fromArray(group));
              })), 0, (function (acc, value) {
            return acc + value.length | 0;
          })));

exports.input = input;
exports.inputList = inputList;
/* input Not a pure module */
