// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var input = Fs.readFileSync("input/Week1/Year2020Day4.sample.txt", "utf8");

var inputList = Belt_Array.map(input.split("\n\n"), (function (passport) {
        return Js_dict.fromArray(Belt_Array.keepMap(Belt_Array.concatMany(Belt_Array.map(passport.split("\n"), (function (item) {
                                  return item.split(" ");
                                }))), (function (item) {
                          var match = item.split(":");
                          if (match.length !== 2) {
                            return ;
                          }
                          var key = match[0];
                          var value = match[1];
                          return [
                                  key,
                                  value
                                ];
                        })));
      }));

var validInputList = Belt_Array.keepMap(inputList, (function (dict) {
        var v = Belt_Int.fromString(Belt_Option.getWithDefault(Js_dict.get(dict, "byr"), ""));
        var match = v !== undefined ? v : undefined;
        var v$1 = Belt_Int.fromString(Belt_Option.getWithDefault(Js_dict.get(dict, "iyr"), ""));
        var match$1 = v$1 !== undefined ? v$1 : undefined;
        var v$2 = Belt_Int.fromString(Belt_Option.getWithDefault(Js_dict.get(dict, "eyr"), ""));
        var match$2 = v$2 !== undefined ? v$2 : undefined;
        var v$3 = Js_dict.get(dict, "hgt");
        var match$3 = v$3 !== undefined ? v$3 : undefined;
        var v$4 = Js_dict.get(dict, "hcl");
        var match$4 = v$4 !== undefined ? v$4 : undefined;
        var v$5 = Js_dict.get(dict, "ecl");
        var match$5 = v$5 !== undefined ? v$5 : undefined;
        var v$6 = Js_dict.get(dict, "pid");
        var match$6 = v$6 !== undefined ? v$6 : undefined;
        var match$7 = Js_dict.get(dict, "cid");
        if (match !== undefined && match$1 !== undefined && match$2 !== undefined && match$3 !== undefined && match$4 !== undefined && match$5 !== undefined && match$6 !== undefined) {
          return {
                  byr: match,
                  iyr: match$1,
                  eyr: match$2,
                  hgt: match$3,
                  hcl: match$4,
                  ecl: match$5,
                  pid: match$6,
                  cid: match$7
                };
        }
        
      }));

console.log(validInputList.length);

exports.input = input;
exports.inputList = inputList;
exports.validInputList = validInputList;
/* input Not a pure module */
