// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var input = Fs.readFileSync("input/Week1/Year2020Day3.sample.txt", "utf8");

var roadMap = input.split("\n");

function getNumberOfTree(roadMap, right, down) {
  var end = roadMap.length - 1 | 0;
  var path = {
    contents: []
  };
  var getPosition = function (x, y) {
    if (y > end) {
      return ;
    }
    var newRight = Caml_int32.mod_(x + right | 0, Caml_array.get(roadMap, y).length);
    getPosition(newRight, y + down | 0);
    path.contents.push(Caml_array.get(roadMap, y).charAt(newRight));
  };
  getPosition(0, down);
  return path.contents.filter(function (item) {
              return item === "#";
            }).length;
}

var resultList = [
  getNumberOfTree(roadMap, 1, 1),
  getNumberOfTree(roadMap, 3, 1),
  getNumberOfTree(roadMap, 5, 1),
  getNumberOfTree(roadMap, 7, 1),
  getNumberOfTree(roadMap, 1, 2)
];

console.log(Belt_Array.reduce(resultList, 1.0, (function (acc, currentVal) {
            return acc * currentVal;
          })));

exports.input = input;
exports.roadMap = roadMap;
exports.getNumberOfTree = getNumberOfTree;
exports.resultList = resultList;
/* input Not a pure module */
